<a href="https://colab.research.google.com/github/divyanshusengar33/ML/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Why pandas ?
import dataset

data cleaning

size mutability

reshaping and pivoting of datasets

efficient manipulation and extraction

staistical analysis

In [115]:
import pandas as pd

In [116]:
s= pd.Series((10,20,30,40,50))
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [117]:
s.dtype

dtype('int64')

In [118]:
s.values

array([10, 20, 30, 40, 50])

In [119]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [120]:
print(s.name)

None

In [121]:
s.name = "calories"

In [122]:
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [123]:
#indexing
s[0]

np.int64(10)

In [124]:
s[0:2] #start(included) : stop(excluded): step value (value to jump)

0    10
1    20
Name: calories, dtype: int64

In [125]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [126]:
# iloc -> location based indexing
s.iloc[3]

np.int64(40)

In [127]:
s.iloc[[1,2,3]]

1    20
2    30
3    40
Name: calories, dtype: int64

In [128]:
index = ["apples", "banana", "grapes","orange","strawberry"]

In [129]:
s.index = index
s

apples        10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [130]:
s['grapes']

np.int64(30)

In [131]:
s.iloc[3]

np.int64(40)

In [132]:
#loc -> label based indexing.
s.loc['grapes']

np.int64(30)

In [133]:
# In label based indexing your start as well as stop value both are included in the output.
s[['banana','grapes']]

banana    20
grapes    30
Name: calories, dtype: int64

In [134]:
fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [135]:
s2 = pd.Series(fruit_protein,name = 'Protein')
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [136]:
# Conditional Selection
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

In [137]:
# Logical Operators : and, or , not
s2[(s2>0.5) & (s2 <= 2)]

Avocado         2.0
Blackberries    2.0
Oranges         0.9
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [138]:
#not operation:
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

###dataframe

In [139]:
import numpy as np

In [140]:
# dataframe

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [141]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [142]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [143]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [144]:
df.tail()

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [145]:
# loc and  iloc

df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [146]:
df.iloc[1:3, :2] #rows, columns

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [147]:
df.loc[1:2, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [148]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [149]:
df.drop("Age", axis = 1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [151]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [150]:
df.shape

(6, 4)

In [152]:
df.info

<bound method DataFrame.info of       Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0>

In [153]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [154]:
#Broadcasting
df["Salary"] =df["Salary"] + 5000

In [155]:
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [176]:
# Renaming columns:
df.rename(columns = {"Department": "Dept"}, inplace = True)

In [177]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [178]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [179]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [180]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [181]:
df["Promoted Salary"] = df["Salary"] * 10

In [183]:
#Data Cleaning
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [184]:
df.dropna(how = "any") # any row that had any null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [186]:
df.dropna(how = "all") #if all the values in any row are null then we drop the row

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [187]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [188]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [189]:
df["Age"].fillna(method = "ffill")

/tmp/ipykernel_8906/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [190]:
df["Age"].fillna(method = "bfill")

/tmp/ipykernel_8906/3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [192]:
df["Name"].replace("Charlie","Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: object

In [193]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [194]:
# Duplicates:

df_dup = df[df.duplicated()]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [195]:
df = df.drop_duplicates()

In [196]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN

In [197]:
# INVALID VALUES
# Lmabda -> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x> 650000 else x)

/tmp/ipykernel_8906/177721503.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x> 650000 else x)

In [198]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eve  29.0       HR      NaN              NaN

In [200]:
name = "alice_fernandes"
df[["first_name","last_name"]] = df["name"].str.split("_")

In [202]:
# apply and lamda
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply(multiplying_age)

/tmp/ipykernel_8906/586814038.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [203]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  50.0       HR  55000.0         550000.0
1      Bob  60.0       IT  65000.0         650000.0
2  Charlie  70.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eve  58.0       HR      NaN              NaN

In [204]:
df["Age"] = df["Age"].apply(lambda x: x/2)

/tmp/ipykernel_8906/1345931692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

In [205]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0          75000.0
3    David   NaN       IT  67000.0          67000.0
4      Eve  29.0       HR      NaN              NaN

In [218]:
# Joins and Merges

department_info = {
    "Dept": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [219]:
pd.concat([df, df2])

      Name   Age     Dept   Salary  Promoted Salary       Location Manager
0    Alice  25.0       HR  55000.0         550000.0            NaN     NaN
1      Bob  30.0       IT  65000.0         650000.0            NaN     NaN
2  Charlie  35.0  Finance  75000.0          75000.0            NaN     NaN
3    David   NaN       IT  67000.0          67000.0            NaN     NaN
4      Eve  29.0       HR      NaN              NaN            NaN     NaN
0      NaN   NaN       HR      NaN              NaN       New York   Laura
1      NaN   NaN       IT      NaN              NaN  San Francisco   Steve
2      NaN   NaN  Finance      NaN              NaN        Chicago    Nina

In [220]:
pd.concat([df, df2], axis = 1)

,Name,Age,Dept,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,25.0,HR,55000.0,550000.0,HR,New York,Laura
1,Bob,30.0,IT,65000.0,650000.0,IT,San Francisco,Steve
2,Charlie,35.0,Finance,75000.0,75000.0,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [221]:
pd.merge(df, df2, on = "Dept")

      Name   Age     Dept   Salary  Promoted Salary       Location Manager
0    Alice  25.0       HR  55000.0         550000.0       New York   Laura
1      Bob  30.0       IT  65000.0         650000.0  San Francisco   Steve
2  Charlie  35.0  Finance  75000.0          75000.0        Chicago    Nina
3    David   NaN       IT  67000.0          67000.0  San Francisco   Steve
4      Eve  29.0       HR      NaN              NaN       New York   Laura

###Importing Rule

In [ ]:
data = pd.read_csv("")